/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author lpzkn
 */
public class InfoAlumno extends javax.swing.JFrame {

    /**
     * Creates new form InfoAlumno
     */
    public InfoAlumno() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        edadspinner = new javax.swing.JSpinner();
        txtnombre = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        combolibro = new javax.swing.JComboBox<>();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        radio1 = new javax.swing.JRadioButton();
        radio3 = new javax.swing.JRadioButton();
        radio2 = new javax.swing.JRadioButton();
        radio4 = new javax.swing.JRadioButton();
        checkest = new javax.swing.JCheckBox();
        checktra = new javax.swing.JCheckBox();
        btnimprimir = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        txtarea = new javax.swing.JTextArea();
        checkmil = new javax.swing.JCheckBox();
        checkpol = new javax.swing.JCheckBox();
        checkfel = new javax.swing.JCheckBox();
        checkdip = new javax.swing.JCheckBox();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Registro-Pedido");

        jPanel1.setBackground(new java.awt.Color(0, 0, 51));
        jPanel1.setForeground(new java.awt.Color(255, 255, 255));

        jLabel1.setFont(new java.awt.Font("Century Gothic", 1, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 204, 0));
        jLabel1.setText("Ingresa los siguientes datos");

        jLabel2.setFont(new java.awt.Font("Century Gothic", 0, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Nombre: ");

        jLabel3.setFont(new java.awt.Font("Century Gothic", 0, 18)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Edad:");

        edadspinner.setModel(new javax.swing.SpinnerNumberModel(0, 0, 120, 1));

        jLabel4.setFont(new java.awt.Font("Century Gothic", 0, 18)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Edicion de libro a solicitar: ");

        combolibro.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "La Biblia.", "Citas del Presidente Mao Tse-Tung (de Mao Tse-Tung).", "Harry Potter (de J.K. Rowling).", "El Señor de los Anillos (J.R.R. Tolkien).", "El Alquimista (de Paulo Coelho).", "El Código da Vinci (de Dan Brown).", "Crepúsculo – La saga (de Stephenie Meyer).", "Lo que el viento se llevó (de Margaret Mitchell)." }));

        jLabel5.setFont(new java.awt.Font("Century Gothic", 0, 18)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("Libro a solicitar");

        jLabel6.setFont(new java.awt.Font("Century Gothic", 0, 18)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("Usted es:");

        radio1.setBackground(new java.awt.Color(255, 153, 0));
        buttonGroup1.add(radio1);
        radio1.setForeground(new java.awt.Color(255, 255, 255));
        radio1.setText("Primera");
        radio1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                radio1ActionPerformed(evt);
            }
        });

        radio3.setBackground(new java.awt.Color(255, 153, 0));
        buttonGroup1.add(radio3);
        radio3.setForeground(new java.awt.Color(255, 255, 255));
        radio3.setText("Tercera");

        radio2.setBackground(new java.awt.Color(255, 153, 0));
        buttonGroup1.add(radio2);
        radio2.setForeground(new java.awt.Color(255, 255, 255));
        radio2.setText("Segunda");

        radio4.setBackground(new java.awt.Color(255, 153, 0));
        buttonGroup1.add(radio4);
        radio4.setForeground(new java.awt.Color(255, 255, 255));
        radio4.setText("Cuarta");

        checkest.setBackground(new java.awt.Color(255, 153, 0));
        checkest.setForeground(new java.awt.Color(255, 255, 255));
        checkest.setText("Estudiante");
        checkest.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                checkestActionPerformed(evt);
            }
        });

        checktra.setBackground(new java.awt.Color(255, 153, 0));
        checktra.setForeground(new java.awt.Color(255, 255, 255));
        checktra.setText("Trabajador");
        checktra.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                checktraActionPerformed(evt);
            }
        });

        btnimprimir.setBackground(new java.awt.Color(255, 0, 0));
        btnimprimir.setForeground(new java.awt.Color(0, 0, 102));
        btnimprimir.setText("Imprimir");
        btnimprimir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnimprimirActionPerformed(evt);
            }
        });

        txtarea.setColumns(20);
        txtarea.setRows(5);
        jScrollPane1.setViewportView(txtarea);

        checkmil.setBackground(new java.awt.Color(255, 153, 0));
        checkmil.setForeground(new java.awt.Color(255, 255, 255));
        checkmil.setText("Millonario");

        checkpol.setBackground(new java.awt.Color(255, 153, 0));
        checkpol.setForeground(new java.awt.Color(255, 255, 255));
        checkpol.setText("Pobre");

        checkfel.setBackground(new java.awt.Color(255, 153, 0));
        checkfel.setForeground(new java.awt.Color(255, 255, 255));
        checkfel.setText("Feliz");

        checkdip.setBackground(new java.awt.Color(255, 153, 0));
        checkdip.setForeground(new java.awt.Color(255, 255, 255));
        checkdip.setText("Diputado");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addGap(54, 54, 54))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(31, 31, 31)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(combolibro, javax.swing.GroupLayout.PREFERRED_SIZE, 282, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel5)
                            .addComponent(jLabel4)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel2)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txtnombre, javax.swing.GroupLayout.PREFERRED_SIZE, 280, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addComponent(jLabel6, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jLabel3, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(edadspinner, javax.swing.GroupLayout.PREFERRED_SIZE, 89, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                            .addComponent(checktra, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                            .addComponent(checkest, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                        .addGap(12, 12, 12)
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                            .addComponent(checkmil, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                            .addComponent(checkpol, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                        .addGap(18, 18, 18)
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                            .addComponent(checkdip, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                            .addComponent(checkfel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(radio2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(radio1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                .addGap(30, 30, 30)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(radio3, javax.swing.GroupLayout.DEFAULT_SIZE, 71, Short.MAX_VALUE)
                                    .addComponent(radio4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                            .addComponent(jScrollPane1)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(169, 169, 169)
                        .addComponent(btnimprimir)))
                .addContainerGap(38, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel2)
                    .addComponent(txtnombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel3)
                    .addComponent(edadspinner, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(checkest)
                    .addComponent(checkmil)
                    .addComponent(checkfel))
                .addGap(8, 8, 8)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(checktra)
                    .addComponent(checkpol)
                    .addComponent(checkdip))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel5)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(combolibro, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(4, 4, 4)
                .addComponent(jLabel4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(radio1)
                    .addComponent(radio3))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(radio2)
                    .addComponent(radio4))
                .addGap(18, 18, 18)
                .addComponent(btnimprimir)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 139, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
    public void edicion(){
if(radio1.isSelected()){
    txtarea.append("\n Edicion: "+"Primera");
}
else if(radio2.isSelected()){ 
    txtarea.append("\n Edicion: "+"Segunda");
}
else if(radio3.isSelected()){ 
    txtarea.append("\n Edicion: "+"Tercera");
}
else if(radio4.isSelected()){ 
    txtarea.append("\n Edicion: "+"Cuarta");
}
}

public void Edad(){
String spin=edadspinner.getValue().toString();
txtarea.append("\n Edad: "+spin);
}   

public void libro(){
String seleccion=(String)combolibro.getSelectedItem();

if(seleccion.equals("La Biblia.")){
txtarea.append("\n Libro: "+"La Biblia.");
}

else if(seleccion.equals("Citas del Presidente Mao Tse-Tung (de Mao Tse-Tung).")){
txtarea.append("\n Libro: "+"Citas del Presidente Mao Tse-Tung (de Mao Tse-Tung).");
}

else if(seleccion.equals("Harry Potter (de J.K. Rowling).")){
txtarea.append("\n Libro: "+"Harry Potter (de J.K. Rowling).");
}

else if(seleccion.equals("El Señor de los Anillos (J.R.R. Tolkien).")){
txtarea.append("\n Libro: "+"El Señor de los Anillos (J.R.R. Tolkien).");
}

else if(seleccion.equals("El Alquimista (de Paulo Coelho).")){
txtarea.append("\n Libro: "+"El Alquimista (de Paulo Coelho).");
}

else if(seleccion.equals("El Código da Vinci (de Dan Brown).")){
txtarea.append("\n Libro: "+"El Código da Vinci (de Dan Brown).");
}

else if(seleccion.equals("Crepúsculo – La saga (de Stephenie Meyer).")){
txtarea.append("\n Libro: "+"Crepúsculo – La saga (de Stephenie Meyer).");
}
else if(seleccion.equals("Lo que el viento se llevó (de Margaret Mitchell).")){
txtarea.append("\n Libro: "+"Lo que el viento se llevó (de Margaret Mitchell).");
}
}
public void UstedEs(){
String mensaje="\n Usted es:";
if(checkest.isSelected()){
mensaje+="- Estudiante ";
}
else if(checktra.isSelected()){
mensaje+="- Trabajador ";
}
if(checkmil.isSelected()){
mensaje+="- Millonario ";
}
else if(checkpol.isSelected()){
mensaje+="- Pobre ";
}
if(checkfel.isSelected()){
mensaje+="- Feliz ";
}
else if(checkdip.isSelected()){
mensaje+="- Diputado ";
}

txtarea.append(mensaje);
}



    private void radio1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_radio1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_radio1ActionPerformed

    private void checkestActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_checkestActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_checkestActionPerformed

    private void btnimprimirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnimprimirActionPerformed
        // TODO add your handling code here:
        String nombre=txtnombre.getText();
        txtarea.setText(" Nombre: "+nombre);
        Edad();
        UstedEs();
        libro();
        edicion();
    }//GEN-LAST:event_btnimprimirActionPerformed

    private void checktraActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_checktraActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_checktraActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(InfoAlumno.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(InfoAlumno.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(InfoAlumno.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(InfoAlumno.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new InfoAlumno().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnimprimir;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JCheckBox checkdip;
    private javax.swing.JCheckBox checkest;
    private javax.swing.JCheckBox checkfel;
    private javax.swing.JCheckBox checkmil;
    private javax.swing.JCheckBox checkpol;
    private javax.swing.JCheckBox checktra;
    private javax.swing.JComboBox<String> combolibro;
    private javax.swing.JSpinner edadspinner;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JRadioButton radio1;
    private javax.swing.JRadioButton radio2;
    private javax.swing.JRadioButton radio3;
    private javax.swing.JRadioButton radio4;
    private javax.swing.JTextArea txtarea;
    private javax.swing.JTextField txtnombre;
    // End of variables declaration//GEN-END:variables
}
